### PR TITLE
Support potentially empty loader options

### PR DESCRIPTION
**Pull request by wbern**
Fixes issue #4

### CODE REVIEW

**Comment by RusinovAnton** [comment]
Have you seen this deprecation warning yet?
https://github.com/webpack/loader-utils/issues/56

**Comment by wbern** [comment]
I specifically mentioned it in my issue. :smile:

**Comment by wintercounter** [comment]
Can we finally have this? It's affecting our processes pretty much now...

**Comment by wintercounter** [comment]
Thank you!

**Pull request merged**
